Remove dependencies from captcha install configuration.
I suspect this is the source of the error during site-install command. The addition of the captcha module was the only revision that included configuration changes and I included an untested adjustment to the exported config where I included dependencies. I added the dependencies here because the configuration applies to certain forms that would not be present of either the core contact module or the webform module were disabled.

Command output:

```
drush site-install realestatepointe_standard --account-mail="[REDACTED]" --account-name="[REDACTED]" --account-pass="[REDACTED]" --site-mail="[REDACTED]" --site-name="[REDACTED]" --yes
```
<snip>
```
in_array() expects parameter 2 to be array, string given
ConfigInstaller.php:571
Error: [] operator not supported for strings in Drupal\Core\Config\ConfigInstaller->getMissingDependencies() (line 572 of /srv/bindings/19952a6ef9fd41fd8a7b3d445eeb51bb/code/web/core/lib/Drupal/Core/Config/ConfigInstaller.php).
Drush command terminated abnormally due to an unrecoverable error.
```